apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    app: tomcat-app
spec:
  type: NodePort
  selector:
    app: tomcat-app
  ports:
    - protocol: TCP
      port: 80     
      targetPort: 8080  
      nodePort: 30007 
